language: erlang
otp_release:
  - 20.0
  - 19.3
install:
  - make
  - ./rebar3 update
before_script:
  - epmd -daemon
script:
  - make test
  - make xref
  - make dialyzer
notifications:
  email: christopher.meiklejohn@gmail.com
  slack: lasp-lang:hiPRNnbUa3zdGrrXZfGRAF7D
  irc: "irc.freenode.org#lasp-lang"
  webhooks: 
      urls:
          - https://webhooks.gitter.im/e/1382c852fbaf2633033a
sudo: false
services:
  - rabbitmq
